// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"Geektime_Go_Camp/第四周/internal/biz"
	"Geektime_Go_Camp/第四周/internal/data"
	"Geektime_Go_Camp/第四周/internal/service"
)

// Injectors from wire.go:

func InitUserService() *service.UserService {
	db := data.NewDB()
	userRepo := data.NewUserRepo(db)
	userBiz := biz.NewUserBiz(userRepo)
	userService := service.NewUserService(userBiz)
	return userService
}
